# Generated by Django 2.2.3 on 2019-07-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.PositiveIntegerField()),
                ('ticker_db', models.CharField(max_length=50)),
                ('report_content', models.CharField(max_length=80)),
                ('latest_pickle_of_the_report', models.CharField(max_length=80)),
            ],
        ),
    ]
