# Generated by Django 2.2.3 on 2019-07-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_generated_time',
            field=models.DateField(default='2017-01-01'),
            preserve_default=False,
        ),
    ]
