# Generated by Django 2.2.3 on 2019-07-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_report_report_generated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_generated_time',
            field=models.DateField(default='2017-01-01'),
        ),
    ]
