# Generated by Django 2.2.3 on 2019-07-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190704_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='phonenumber',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
