# Generated by Django 2.2.3 on 2019-07-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_report_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_db', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=80)),
                ('latest_pickle_of_model', models.CharField(max_length=80)),
                ('standardized_conviction_score', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_id',
        ),
    ]
