# Generated by Django 2.2.3 on 2019-07-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_predictions_latest_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_generated_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
