# Generated by Django 2.2.3 on 2019-07-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heat_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_db', models.CharField(max_length=80)),
                ('LINEAR_REGRESSION', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('LOGISTIC_REGRESSION', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('LSTM_1', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('LSTM_2', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('LDS_190101', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('REL_VAL_1', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('SUMMARY_SC_SCORE', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
            ],
        ),
    ]
