# Generated by Django 2.2.3 on 2019-07-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_heat_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='heat_map',
            name='M2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
